proxy-providers:
  PG_SSHOCEAN:
    type: http
    path: "./proxy_provider/SSHOCEAN.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_xl_me/main/VLESS/SSHOCEAN.yaml
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 10
  PG_FASTSSH:
    type: http
    path: "./proxy_provider/FASTSSH.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_xl_me/main/VLESS/FASTSSH.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 10
  PG_OPENTUNNEL:
    type: http
    path: "./proxy_provider/OPENTUNNEL.yaml"
    url: https://raw.githubusercontent.com/Afqoro/cfa_xl_me/main/VLESS/OPENTUNNEL.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 10
proxy-groups:
- name: SSHOCEAN
  type: url-test
  disable-udp: false
  use:
  - PG_SSHOCEAN
  url: http://www.gstatic.com/generate_204
  interval: '10'
  tolerance: '5'
- name: FASTSSH
  type: url-test
  disable-udp: false
  use:
  - PG_FASTSSH
  url: http://www.gstatic.com/generate_204
  interval: '10'
  tolerance: '5'
- name: OPENTUNNEL
  type: url-test
  disable-udp: false
  use:
  - PG_OPENTUNNEL
  url: http://www.gstatic.com/generate_204
  interval: '10'
  tolerance: '5'
- name: PILIHAN
  type: select
  disable-udp: false
  use:
  - PG_SSHOCEAN
  - PG_OPENTUNNEL
  - PG_FASTSSH
  url: http://www.gstatic.com/generate_204
  interval: '10'
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 1.0.0.1
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - 112.215.203.254
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 112.215.203.254
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- MATCH,GLOBAL